development:
  adapter: postgresql
  encoding: unicode
  database: jsrepl_development
  pool: 5
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: jsrepl_test
  pool: 5
  host: localhost
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: new_production
  pool: 5
  username: new
  password:
